### ISSUE TITLE
Database init is not working

### ISSUE THREAD

**Issue by Scriptkiddi** [stuvusIT/postgresql#10]
fatal: [vagrant]: FAILED! => {"changed": true, "cmd": ["sud
o", "-Hu", "postgres", "/usr/lib/postgresql/9.5/bin/initdb"
, "--locale", "C", "-E", "UTF8", "-D", "/var/lib/postgres"]
, "delta": "0:00:00.013427", "end": "2017-10-08 23:04:47.39
1783", "failed": true, "msg": "non-zero return code", "rc":
 1, "start": "2017-10-08 23:04:47.378356", "stderr": "initd
b: directory \"/var/lib/postgres\" exists but is not empty\
nIt contains a dot-prefixed/invisible file, perhaps due to
it being a mount point.\nUsing a mount point directly as th
e data directory is not recommended.\nCreate a subdirectory
 under the mount point.", "stderr_lines": ["initdb: directo
ry \"/var/lib/postgres\" exists but is not empty", "It cont
ains a dot-prefixed/invisible file, perhaps due to it being
 a mount point.", "Using a mount point directly as the data
 directory is not recommended.", "Create a subdirectory und
er the mount point."], "stdout": "The files belonging to th
is database system will be owned by user \"postgres\".\nThi
s user must also own the server process.\n\nThe database cl
uster will be initialized with locale \"C\".\nThe default t
ext search configuration will be set to \"english\".\n\nDat
a page checksums are disabled.", "stdout_lines": ["The file
s belonging to this database system will be owned by user \
"postgres\".", "This user must also own the server process.
", "", "The database cluster will be initialized with local
e \"C\".", "The default text search configuration will be s
et to \"english\".", "", "Data page checksums are disabled.
"]}

**Comment by dasJ** [comment]
Fixed with #8
