### ISSUE TITLE
Multiple instances are starting

### ISSUE THREAD

**Issue by Scriptkiddi** [stuvusIT/postgresql#19]
when you install an instance ubuntu by default starts some shit service and then the postgresql.service does not come up since the port is already in use

**Comment by dasJ** [comment]
Automatically bumping this issue because it was inactive for 36 days.

**Comment by dasJ** [comment]
Automatically bumping this issue because it was inactive for 55 days.

**Comment by Scriptkiddi** [comment]
Automatically bumping this issue because it was inactive for 55 days.
