### ISSUE TITLE
path to initdb

### ISSUE THREAD

**Issue by Scriptkiddi** [stuvusIT/postgresql#20]
Please add initdb to the path on ubuntu systems otherwise you pin the version by passing initdb in

**Comment by dasJ** [comment]
Automatically bumping this issue because it was inactive for 14 days.

**Comment by dasJ** [comment]
Automatically bumping this issue because it was inactive for 33 days.

**Comment by Scriptkiddi** [comment]
Automatically bumping this issue because it was inactive for 33 days.
